namespace RestaurantManagementSystem
{
    partial class MainActivity
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainActivity));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.ControlsPanel = new System.Windows.Forms.Panel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.categoryBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.logoutBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.reportsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.staffBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.IngredientsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.ProductsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.dashboardBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // ControlsPanel
            // 
            this.ControlsPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ControlsPanel.Location = new System.Drawing.Point(200, 100);
            this.ControlsPanel.Name = "ControlsPanel";
            this.ControlsPanel.Size = new System.Drawing.Size(1100, 800);
            this.ControlsPanel.TabIndex = 3;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.Location = new System.Drawing.Point(200, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(1100, 100);
            this.bunifuPanel2.TabIndex = 2;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(160)))), ((int)(((byte)(31)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.dashboardBtn);
            this.bunifuPanel1.Controls.Add(this.categoryBtn);
            this.bunifuPanel1.Controls.Add(this.logoutBtn);
            this.bunifuPanel1.Controls.Add(this.reportsBtn);
            this.bunifuPanel1.Controls.Add(this.staffBtn);
            this.bunifuPanel1.Controls.Add(this.IngredientsBtn);
            this.bunifuPanel1.Controls.Add(this.ProductsBtn);
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(200, 900);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // categoryBtn
            // 
            this.categoryBtn.AllowAnimations = true;
            this.categoryBtn.AllowMouseEffects = true;
            this.categoryBtn.AllowToggling = false;
            this.categoryBtn.AnimationSpeed = 200;
            this.categoryBtn.AutoGenerateColors = false;
            this.categoryBtn.AutoRoundBorders = false;
            this.categoryBtn.AutoSizeLeftIcon = true;
            this.categoryBtn.AutoSizeRightIcon = true;
            this.categoryBtn.BackColor = System.Drawing.Color.Transparent;
            this.categoryBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.categoryBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("categoryBtn.BackgroundImage")));
            this.categoryBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryBtn.ButtonText = "Category";
            this.categoryBtn.ButtonTextMarginLeft = 0;
            this.categoryBtn.ColorContrastOnClick = 45;
            this.categoryBtn.ColorContrastOnHover = 45;
            this.categoryBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = false;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = false;
            this.categoryBtn.CustomizableEdges = borderEdges2;
            this.categoryBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.categoryBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoryBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoryBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoryBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.categoryBtn.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.categoryBtn.ForeColor = System.Drawing.Color.Black;
            this.categoryBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.categoryBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.categoryBtn.IconLeftPadding = new System.Windows.Forms.Padding(12, 4, 3, 3);
            this.categoryBtn.IconMarginLeft = 11;
            this.categoryBtn.IconPadding = 10;
            this.categoryBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.categoryBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.categoryBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.categoryBtn.IconSize = 30;
            this.categoryBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.categoryBtn.IdleBorderRadius = 34;
            this.categoryBtn.IdleBorderThickness = 1;
            this.categoryBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.categoryBtn.IdleIconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_categories_45;
            this.categoryBtn.IdleIconRightImage = null;
            this.categoryBtn.IndicateFocus = false;
            this.categoryBtn.Location = new System.Drawing.Point(42, 271);
            this.categoryBtn.Name = "categoryBtn";
            this.categoryBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoryBtn.OnDisabledState.BorderRadius = 34;
            this.categoryBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryBtn.OnDisabledState.BorderThickness = 1;
            this.categoryBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoryBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoryBtn.OnDisabledState.IconLeftImage = null;
            this.categoryBtn.OnDisabledState.IconRightImage = null;
            this.categoryBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.categoryBtn.onHoverState.BorderRadius = 34;
            this.categoryBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryBtn.onHoverState.BorderThickness = 1;
            this.categoryBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.categoryBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.categoryBtn.onHoverState.IconLeftImage = null;
            this.categoryBtn.onHoverState.IconRightImage = null;
            this.categoryBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.categoryBtn.OnIdleState.BorderRadius = 34;
            this.categoryBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryBtn.OnIdleState.BorderThickness = 1;
            this.categoryBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.categoryBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.categoryBtn.OnIdleState.IconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_categories_45;
            this.categoryBtn.OnIdleState.IconRightImage = null;
            this.categoryBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.categoryBtn.OnPressedState.BorderRadius = 34;
            this.categoryBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryBtn.OnPressedState.BorderThickness = 1;
            this.categoryBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.categoryBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.categoryBtn.OnPressedState.IconLeftImage = null;
            this.categoryBtn.OnPressedState.IconRightImage = null;
            this.categoryBtn.Size = new System.Drawing.Size(158, 45);
            this.categoryBtn.TabIndex = 9;
            this.categoryBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.categoryBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.categoryBtn.TextMarginLeft = 0;
            this.categoryBtn.TextPadding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.categoryBtn.UseDefaultRadiusAndThickness = true;
            this.categoryBtn.Click += new System.EventHandler(this.categoryBtn_Click);
            // 
            // logoutBtn
            // 
            this.logoutBtn.AllowAnimations = true;
            this.logoutBtn.AllowMouseEffects = true;
            this.logoutBtn.AllowToggling = false;
            this.logoutBtn.AnimationSpeed = 200;
            this.logoutBtn.AutoGenerateColors = false;
            this.logoutBtn.AutoRoundBorders = true;
            this.logoutBtn.AutoSizeLeftIcon = true;
            this.logoutBtn.AutoSizeRightIcon = true;
            this.logoutBtn.BackColor = System.Drawing.Color.Transparent;
            this.logoutBtn.BackColor1 = System.Drawing.Color.Black;
            this.logoutBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("logoutBtn.BackgroundImage")));
            this.logoutBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logoutBtn.ButtonText = "Logout";
            this.logoutBtn.ButtonTextMarginLeft = 0;
            this.logoutBtn.ColorContrastOnClick = 45;
            this.logoutBtn.ColorContrastOnHover = 45;
            this.logoutBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.logoutBtn.CustomizableEdges = borderEdges3;
            this.logoutBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.logoutBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.logoutBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.logoutBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.logoutBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.logoutBtn.Font = new System.Drawing.Font("Poppins", 12.5F);
            this.logoutBtn.ForeColor = System.Drawing.Color.White;
            this.logoutBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.logoutBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.logoutBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.logoutBtn.IconMarginLeft = 11;
            this.logoutBtn.IconPadding = 10;
            this.logoutBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.logoutBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.logoutBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.logoutBtn.IconSize = 25;
            this.logoutBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.logoutBtn.IdleBorderRadius = 37;
            this.logoutBtn.IdleBorderThickness = 1;
            this.logoutBtn.IdleFillColor = System.Drawing.Color.Black;
            this.logoutBtn.IdleIconLeftImage = null;
            this.logoutBtn.IdleIconRightImage = null;
            this.logoutBtn.IndicateFocus = false;
            this.logoutBtn.Location = new System.Drawing.Point(25, 811);
            this.logoutBtn.Name = "logoutBtn";
            this.logoutBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.logoutBtn.OnDisabledState.BorderRadius = 1;
            this.logoutBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logoutBtn.OnDisabledState.BorderThickness = 1;
            this.logoutBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.logoutBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.logoutBtn.OnDisabledState.IconLeftImage = null;
            this.logoutBtn.OnDisabledState.IconRightImage = null;
            this.logoutBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.logoutBtn.onHoverState.BorderRadius = 1;
            this.logoutBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logoutBtn.onHoverState.BorderThickness = 1;
            this.logoutBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.logoutBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.logoutBtn.onHoverState.IconLeftImage = null;
            this.logoutBtn.onHoverState.IconRightImage = null;
            this.logoutBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.logoutBtn.OnIdleState.BorderRadius = 1;
            this.logoutBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logoutBtn.OnIdleState.BorderThickness = 1;
            this.logoutBtn.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.logoutBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.logoutBtn.OnIdleState.IconLeftImage = null;
            this.logoutBtn.OnIdleState.IconRightImage = null;
            this.logoutBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.logoutBtn.OnPressedState.BorderRadius = 1;
            this.logoutBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logoutBtn.OnPressedState.BorderThickness = 1;
            this.logoutBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.logoutBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.logoutBtn.OnPressedState.IconLeftImage = null;
            this.logoutBtn.OnPressedState.IconRightImage = null;
            this.logoutBtn.Size = new System.Drawing.Size(150, 39);
            this.logoutBtn.TabIndex = 8;
            this.logoutBtn.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.logoutBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.logoutBtn.TextMarginLeft = 0;
            this.logoutBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.logoutBtn.UseDefaultRadiusAndThickness = true;
            // 
            // reportsBtn
            // 
            this.reportsBtn.AllowAnimations = true;
            this.reportsBtn.AllowMouseEffects = true;
            this.reportsBtn.AllowToggling = false;
            this.reportsBtn.AnimationSpeed = 200;
            this.reportsBtn.AutoGenerateColors = false;
            this.reportsBtn.AutoRoundBorders = false;
            this.reportsBtn.AutoSizeLeftIcon = true;
            this.reportsBtn.AutoSizeRightIcon = true;
            this.reportsBtn.BackColor = System.Drawing.Color.Transparent;
            this.reportsBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.reportsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("reportsBtn.BackgroundImage")));
            this.reportsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.reportsBtn.ButtonText = "Reports";
            this.reportsBtn.ButtonTextMarginLeft = 0;
            this.reportsBtn.ColorContrastOnClick = 45;
            this.reportsBtn.ColorContrastOnHover = 45;
            this.reportsBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = false;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = false;
            this.reportsBtn.CustomizableEdges = borderEdges4;
            this.reportsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.reportsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportsBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportsBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.reportsBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.reportsBtn.ForeColor = System.Drawing.Color.Black;
            this.reportsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.reportsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.reportsBtn.IconLeftPadding = new System.Windows.Forms.Padding(12, 4, 3, 3);
            this.reportsBtn.IconMarginLeft = 11;
            this.reportsBtn.IconPadding = 10;
            this.reportsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.reportsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.reportsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.reportsBtn.IconSize = 30;
            this.reportsBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.reportsBtn.IdleBorderRadius = 34;
            this.reportsBtn.IdleBorderThickness = 1;
            this.reportsBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.reportsBtn.IdleIconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_test_results_45;
            this.reportsBtn.IdleIconRightImage = null;
            this.reportsBtn.IndicateFocus = false;
            this.reportsBtn.Location = new System.Drawing.Point(42, 574);
            this.reportsBtn.Name = "reportsBtn";
            this.reportsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportsBtn.OnDisabledState.BorderRadius = 34;
            this.reportsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.reportsBtn.OnDisabledState.BorderThickness = 1;
            this.reportsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportsBtn.OnDisabledState.IconLeftImage = null;
            this.reportsBtn.OnDisabledState.IconRightImage = null;
            this.reportsBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.reportsBtn.onHoverState.BorderRadius = 34;
            this.reportsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.reportsBtn.onHoverState.BorderThickness = 1;
            this.reportsBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.reportsBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.reportsBtn.onHoverState.IconLeftImage = null;
            this.reportsBtn.onHoverState.IconRightImage = null;
            this.reportsBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.reportsBtn.OnIdleState.BorderRadius = 34;
            this.reportsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.reportsBtn.OnIdleState.BorderThickness = 1;
            this.reportsBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.reportsBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.reportsBtn.OnIdleState.IconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_test_results_45;
            this.reportsBtn.OnIdleState.IconRightImage = null;
            this.reportsBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.reportsBtn.OnPressedState.BorderRadius = 34;
            this.reportsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.reportsBtn.OnPressedState.BorderThickness = 1;
            this.reportsBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.reportsBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.reportsBtn.OnPressedState.IconLeftImage = null;
            this.reportsBtn.OnPressedState.IconRightImage = null;
            this.reportsBtn.Size = new System.Drawing.Size(158, 45);
            this.reportsBtn.TabIndex = 2;
            this.reportsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.reportsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.reportsBtn.TextMarginLeft = 0;
            this.reportsBtn.TextPadding = new System.Windows.Forms.Padding(2, 0, 0, 0);
            this.reportsBtn.UseDefaultRadiusAndThickness = true;
            this.reportsBtn.Click += new System.EventHandler(this.reportsBtn_Click);
            // 
            // staffBtn
            // 
            this.staffBtn.AllowAnimations = true;
            this.staffBtn.AllowMouseEffects = true;
            this.staffBtn.AllowToggling = false;
            this.staffBtn.AnimationSpeed = 200;
            this.staffBtn.AutoGenerateColors = false;
            this.staffBtn.AutoRoundBorders = false;
            this.staffBtn.AutoSizeLeftIcon = true;
            this.staffBtn.AutoSizeRightIcon = true;
            this.staffBtn.BackColor = System.Drawing.Color.Transparent;
            this.staffBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.staffBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("staffBtn.BackgroundImage")));
            this.staffBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.staffBtn.ButtonText = "Staff";
            this.staffBtn.ButtonTextMarginLeft = 0;
            this.staffBtn.ColorContrastOnClick = 45;
            this.staffBtn.ColorContrastOnHover = 45;
            this.staffBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = false;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = false;
            this.staffBtn.CustomizableEdges = borderEdges5;
            this.staffBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.staffBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.staffBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.staffBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.staffBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.staffBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.staffBtn.ForeColor = System.Drawing.Color.Black;
            this.staffBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.staffBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.staffBtn.IconLeftPadding = new System.Windows.Forms.Padding(12, 4, 3, 3);
            this.staffBtn.IconMarginLeft = 11;
            this.staffBtn.IconPadding = 10;
            this.staffBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.staffBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.staffBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.staffBtn.IconSize = 30;
            this.staffBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.staffBtn.IdleBorderRadius = 34;
            this.staffBtn.IdleBorderThickness = 1;
            this.staffBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.staffBtn.IdleIconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_staff_45;
            this.staffBtn.IdleIconRightImage = null;
            this.staffBtn.IndicateFocus = false;
            this.staffBtn.Location = new System.Drawing.Point(42, 498);
            this.staffBtn.Name = "staffBtn";
            this.staffBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.staffBtn.OnDisabledState.BorderRadius = 34;
            this.staffBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.staffBtn.OnDisabledState.BorderThickness = 1;
            this.staffBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.staffBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.staffBtn.OnDisabledState.IconLeftImage = null;
            this.staffBtn.OnDisabledState.IconRightImage = null;
            this.staffBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.staffBtn.onHoverState.BorderRadius = 34;
            this.staffBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.staffBtn.onHoverState.BorderThickness = 1;
            this.staffBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.staffBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.staffBtn.onHoverState.IconLeftImage = null;
            this.staffBtn.onHoverState.IconRightImage = null;
            this.staffBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.staffBtn.OnIdleState.BorderRadius = 34;
            this.staffBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.staffBtn.OnIdleState.BorderThickness = 1;
            this.staffBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.staffBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.staffBtn.OnIdleState.IconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_staff_45;
            this.staffBtn.OnIdleState.IconRightImage = null;
            this.staffBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.staffBtn.OnPressedState.BorderRadius = 34;
            this.staffBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.staffBtn.OnPressedState.BorderThickness = 1;
            this.staffBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.staffBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.staffBtn.OnPressedState.IconLeftImage = null;
            this.staffBtn.OnPressedState.IconRightImage = null;
            this.staffBtn.Size = new System.Drawing.Size(158, 45);
            this.staffBtn.TabIndex = 2;
            this.staffBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.staffBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.staffBtn.TextMarginLeft = 0;
            this.staffBtn.TextPadding = new System.Windows.Forms.Padding(-10, 0, 0, 0);
            this.staffBtn.UseDefaultRadiusAndThickness = true;
            this.staffBtn.Click += new System.EventHandler(this.staffBtn_Click);
            // 
            // IngredientsBtn
            // 
            this.IngredientsBtn.AllowAnimations = true;
            this.IngredientsBtn.AllowMouseEffects = true;
            this.IngredientsBtn.AllowToggling = false;
            this.IngredientsBtn.AnimationSpeed = 200;
            this.IngredientsBtn.AutoGenerateColors = false;
            this.IngredientsBtn.AutoRoundBorders = false;
            this.IngredientsBtn.AutoSizeLeftIcon = true;
            this.IngredientsBtn.AutoSizeRightIcon = true;
            this.IngredientsBtn.BackColor = System.Drawing.Color.Transparent;
            this.IngredientsBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.IngredientsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("IngredientsBtn.BackgroundImage")));
            this.IngredientsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.IngredientsBtn.ButtonText = "Ingredients";
            this.IngredientsBtn.ButtonTextMarginLeft = 0;
            this.IngredientsBtn.ColorContrastOnClick = 45;
            this.IngredientsBtn.ColorContrastOnHover = 45;
            this.IngredientsBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = false;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = false;
            this.IngredientsBtn.CustomizableEdges = borderEdges6;
            this.IngredientsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.IngredientsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.IngredientsBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.IngredientsBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.IngredientsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.IngredientsBtn.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.IngredientsBtn.ForeColor = System.Drawing.Color.Black;
            this.IngredientsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.IngredientsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.IngredientsBtn.IconLeftPadding = new System.Windows.Forms.Padding(12, 4, 3, 3);
            this.IngredientsBtn.IconMarginLeft = 11;
            this.IngredientsBtn.IconPadding = 10;
            this.IngredientsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.IngredientsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.IngredientsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.IngredientsBtn.IconSize = 30;
            this.IngredientsBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.IngredientsBtn.IdleBorderRadius = 34;
            this.IngredientsBtn.IdleBorderThickness = 1;
            this.IngredientsBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.IngredientsBtn.IdleIconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_ingredients_45;
            this.IngredientsBtn.IdleIconRightImage = null;
            this.IngredientsBtn.IndicateFocus = false;
            this.IngredientsBtn.Location = new System.Drawing.Point(42, 422);
            this.IngredientsBtn.Name = "IngredientsBtn";
            this.IngredientsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.IngredientsBtn.OnDisabledState.BorderRadius = 34;
            this.IngredientsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.IngredientsBtn.OnDisabledState.BorderThickness = 1;
            this.IngredientsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.IngredientsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.IngredientsBtn.OnDisabledState.IconLeftImage = null;
            this.IngredientsBtn.OnDisabledState.IconRightImage = null;
            this.IngredientsBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.IngredientsBtn.onHoverState.BorderRadius = 34;
            this.IngredientsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.IngredientsBtn.onHoverState.BorderThickness = 1;
            this.IngredientsBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.IngredientsBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.IngredientsBtn.onHoverState.IconLeftImage = null;
            this.IngredientsBtn.onHoverState.IconRightImage = null;
            this.IngredientsBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.IngredientsBtn.OnIdleState.BorderRadius = 34;
            this.IngredientsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.IngredientsBtn.OnIdleState.BorderThickness = 1;
            this.IngredientsBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.IngredientsBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.IngredientsBtn.OnIdleState.IconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_ingredients_45;
            this.IngredientsBtn.OnIdleState.IconRightImage = null;
            this.IngredientsBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.IngredientsBtn.OnPressedState.BorderRadius = 34;
            this.IngredientsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.IngredientsBtn.OnPressedState.BorderThickness = 1;
            this.IngredientsBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.IngredientsBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.IngredientsBtn.OnPressedState.IconLeftImage = null;
            this.IngredientsBtn.OnPressedState.IconRightImage = null;
            this.IngredientsBtn.Size = new System.Drawing.Size(158, 45);
            this.IngredientsBtn.TabIndex = 2;
            this.IngredientsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.IngredientsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.IngredientsBtn.TextMarginLeft = 0;
            this.IngredientsBtn.TextPadding = new System.Windows.Forms.Padding(16, 0, 0, 0);
            this.IngredientsBtn.UseDefaultRadiusAndThickness = true;
            this.IngredientsBtn.Click += new System.EventHandler(this.IngredientsBtn_Click);
            // 
            // ProductsBtn
            // 
            this.ProductsBtn.AllowAnimations = true;
            this.ProductsBtn.AllowMouseEffects = true;
            this.ProductsBtn.AllowToggling = false;
            this.ProductsBtn.AnimationSpeed = 200;
            this.ProductsBtn.AutoGenerateColors = false;
            this.ProductsBtn.AutoRoundBorders = false;
            this.ProductsBtn.AutoSizeLeftIcon = true;
            this.ProductsBtn.AutoSizeRightIcon = true;
            this.ProductsBtn.BackColor = System.Drawing.Color.Transparent;
            this.ProductsBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.ProductsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductsBtn.BackgroundImage")));
            this.ProductsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ProductsBtn.ButtonText = "Products";
            this.ProductsBtn.ButtonTextMarginLeft = 0;
            this.ProductsBtn.ColorContrastOnClick = 45;
            this.ProductsBtn.ColorContrastOnHover = 45;
            this.ProductsBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = false;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = false;
            this.ProductsBtn.CustomizableEdges = borderEdges7;
            this.ProductsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ProductsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProductsBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductsBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProductsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.ProductsBtn.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ProductsBtn.ForeColor = System.Drawing.Color.Black;
            this.ProductsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ProductsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ProductsBtn.IconLeftPadding = new System.Windows.Forms.Padding(12, 4, 3, 3);
            this.ProductsBtn.IconMarginLeft = 11;
            this.ProductsBtn.IconPadding = 10;
            this.ProductsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ProductsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ProductsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ProductsBtn.IconSize = 30;
            this.ProductsBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.ProductsBtn.IdleBorderRadius = 34;
            this.ProductsBtn.IdleBorderThickness = 1;
            this.ProductsBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.ProductsBtn.IdleIconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_basket_45;
            this.ProductsBtn.IdleIconRightImage = null;
            this.ProductsBtn.IndicateFocus = false;
            this.ProductsBtn.Location = new System.Drawing.Point(42, 346);
            this.ProductsBtn.Name = "ProductsBtn";
            this.ProductsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProductsBtn.OnDisabledState.BorderRadius = 34;
            this.ProductsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ProductsBtn.OnDisabledState.BorderThickness = 1;
            this.ProductsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProductsBtn.OnDisabledState.IconLeftImage = null;
            this.ProductsBtn.OnDisabledState.IconRightImage = null;
            this.ProductsBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductsBtn.onHoverState.BorderRadius = 34;
            this.ProductsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ProductsBtn.onHoverState.BorderThickness = 1;
            this.ProductsBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductsBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ProductsBtn.onHoverState.IconLeftImage = null;
            this.ProductsBtn.onHoverState.IconRightImage = null;
            this.ProductsBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.ProductsBtn.OnIdleState.BorderRadius = 34;
            this.ProductsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ProductsBtn.OnIdleState.BorderThickness = 1;
            this.ProductsBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.ProductsBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.ProductsBtn.OnIdleState.IconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_basket_45;
            this.ProductsBtn.OnIdleState.IconRightImage = null;
            this.ProductsBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProductsBtn.OnPressedState.BorderRadius = 34;
            this.ProductsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ProductsBtn.OnPressedState.BorderThickness = 1;
            this.ProductsBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProductsBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ProductsBtn.OnPressedState.IconLeftImage = null;
            this.ProductsBtn.OnPressedState.IconRightImage = null;
            this.ProductsBtn.Size = new System.Drawing.Size(158, 45);
            this.ProductsBtn.TabIndex = 2;
            this.ProductsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ProductsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ProductsBtn.TextMarginLeft = 0;
            this.ProductsBtn.TextPadding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.ProductsBtn.UseDefaultRadiusAndThickness = true;
            this.ProductsBtn.Click += new System.EventHandler(this.ProductsBtn_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = global::RestaurantManagementSystem.Properties.Resources.logo;
            this.pictureBox1.Location = new System.Drawing.Point(42, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(115, 108);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // dashboardBtn
            // 
            this.dashboardBtn.AllowAnimations = true;
            this.dashboardBtn.AllowMouseEffects = true;
            this.dashboardBtn.AllowToggling = false;
            this.dashboardBtn.AnimationSpeed = 200;
            this.dashboardBtn.AutoGenerateColors = false;
            this.dashboardBtn.AutoRoundBorders = false;
            this.dashboardBtn.AutoSizeLeftIcon = true;
            this.dashboardBtn.AutoSizeRightIcon = true;
            this.dashboardBtn.BackColor = System.Drawing.Color.Transparent;
            this.dashboardBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.dashboardBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dashboardBtn.BackgroundImage")));
            this.dashboardBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.dashboardBtn.ButtonText = "Dashboard";
            this.dashboardBtn.ButtonTextMarginLeft = 0;
            this.dashboardBtn.ColorContrastOnClick = 45;
            this.dashboardBtn.ColorContrastOnHover = 45;
            this.dashboardBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = false;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = false;
            this.dashboardBtn.CustomizableEdges = borderEdges1;
            this.dashboardBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.dashboardBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.dashboardBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dashboardBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.dashboardBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.dashboardBtn.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dashboardBtn.ForeColor = System.Drawing.Color.Black;
            this.dashboardBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.dashboardBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.dashboardBtn.IconLeftPadding = new System.Windows.Forms.Padding(12, 4, 3, 3);
            this.dashboardBtn.IconMarginLeft = 11;
            this.dashboardBtn.IconPadding = 10;
            this.dashboardBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.dashboardBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.dashboardBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.dashboardBtn.IconSize = 30;
            this.dashboardBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.dashboardBtn.IdleBorderRadius = 34;
            this.dashboardBtn.IdleBorderThickness = 1;
            this.dashboardBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.dashboardBtn.IdleIconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_home_45;
            this.dashboardBtn.IdleIconRightImage = null;
            this.dashboardBtn.IndicateFocus = false;
            this.dashboardBtn.Location = new System.Drawing.Point(42, 195);
            this.dashboardBtn.Name = "dashboardBtn";
            this.dashboardBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.dashboardBtn.OnDisabledState.BorderRadius = 34;
            this.dashboardBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.dashboardBtn.OnDisabledState.BorderThickness = 1;
            this.dashboardBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dashboardBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.dashboardBtn.OnDisabledState.IconLeftImage = null;
            this.dashboardBtn.OnDisabledState.IconRightImage = null;
            this.dashboardBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.dashboardBtn.onHoverState.BorderRadius = 34;
            this.dashboardBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.dashboardBtn.onHoverState.BorderThickness = 1;
            this.dashboardBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.dashboardBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.dashboardBtn.onHoverState.IconLeftImage = null;
            this.dashboardBtn.onHoverState.IconRightImage = null;
            this.dashboardBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.dashboardBtn.OnIdleState.BorderRadius = 34;
            this.dashboardBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.dashboardBtn.OnIdleState.BorderThickness = 1;
            this.dashboardBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(95)))), ((int)(((byte)(89)))));
            this.dashboardBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.dashboardBtn.OnIdleState.IconLeftImage = global::RestaurantManagementSystem.Properties.Resources.icons8_home_45;
            this.dashboardBtn.OnIdleState.IconRightImage = null;
            this.dashboardBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.dashboardBtn.OnPressedState.BorderRadius = 34;
            this.dashboardBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.dashboardBtn.OnPressedState.BorderThickness = 1;
            this.dashboardBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.dashboardBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.dashboardBtn.OnPressedState.IconLeftImage = null;
            this.dashboardBtn.OnPressedState.IconRightImage = null;
            this.dashboardBtn.Size = new System.Drawing.Size(158, 45);
            this.dashboardBtn.TabIndex = 9;
            this.dashboardBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.dashboardBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.dashboardBtn.TextMarginLeft = 0;
            this.dashboardBtn.TextPadding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.dashboardBtn.UseDefaultRadiusAndThickness = true;
            this.dashboardBtn.Click += new System.EventHandler(this.dashboardBtn_Click);
            // 
            // MainActivity
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1300, 900);
            this.Controls.Add(this.ControlsPanel);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "MainActivity";
            this.Text = "MainActivity";
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 categoryBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 logoutBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 reportsBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 staffBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 IngredientsBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 ProductsBtn;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private System.Windows.Forms.Panel ControlsPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 dashboardBtn;
    }
}